# Generated by Django 4.1.11 on 2023-10-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='studentAWS',
        ),
    ]
